# Generated by Django 3.1.7 on 2021-03-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Five_Cent', '0008_auto_20210303_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main_product/'),
        ),
    ]
